#!/usr/bin/env python3

import glib, json, dbus, dbus.service, time, sys
from dbus.mainloop.glib import DBusGMainLoop

class DStatusService(dbus.service.Object):
    def __init__(self):
        bus_name = dbus.service.BusName('com.dubstepdish.i3dstatus', bus=dbus.SessionBus())
        dbus.service.Object.__init__(self, bus_name, '/com/dubstepdish/i3dstatus')
        self.blocks = []

    @dbus.service.method('com.dubstepdish.i3dstatus', in_signature='a{sv}')
    def show_block(self, block):
        block_found = False
        for i,b in enumerate(self.blocks):
            if b['name'] == block['name']:
                block_found = True
                self.blocks[i] = block

        if not block_found:
            self.blocks.append(block)

        # filter out blocks with no 'full_text' member
        self.blocks = [b for b in self.blocks if 'full_text' in b and b['full_text'] != '']
        # sort by block name (right aligned)
        self.blocks.sort(key=lambda b: str.lower(b['name']), reverse=True)

        sys.stdout.write(',' + json.dumps(self.blocks) + '\n')
        sys.stdout.flush()

DBusGMainLoop(set_as_default=True)
service = DStatusService()

sys.stdout.write('{"version":1}\n[\n[]\n')
sys.stdout.flush()

main = glib.MainLoop()
main.run()
