#!/usr/bin/env python3

from gi.repository import Gtk, GLib, Gdk
import dbus
import cgi

i3dstatus = dbus.Interface(
    dbus.SessionBus().get_object('com.dubstepdish.i3dstatus', '/com/dubstepdish/i3dstatus'),
    'com.dubstepdish.i3dstatus.Manager'
)

config = i3dstatus.get_config('clipboard')

clipboard_format = config.get('format', '<span size="small" font="FontAwesome">\uf0ea</span> %text')
truncate_length = config.get('truncate-length', 20)

clipboard = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)


def format_clipboard_text(cb_text):
    cb_text = cgi.escape(cb_text.replace('\n', ''))

    if len(cb_text) > truncate_length:
        cb_text = cb_text[0:truncate_length].rstrip() + '…'

    cb_text = clipboard_format.replace('%text', cb_text)

    return cb_text


def on_owner_change(clipboard, event):
    cb_text = clipboard.wait_for_text()
    print("Clipboard", cb_text)

    if not cb_text:
        # no clipboard, so clear the block
        block.update({"full_text": ""})
    else:
        block.update({
            "full_text": format_clipboard_text(cb_text),
            "markup": "pango"
        })

cb_text = clipboard.wait_for_text()

blockpath = i3dstatus.create_block(
    'clipboard',
    {
        "name": "clipboard",
        "full_text": format_clipboard_text(cb_text),
        "markup": "pango"
    })

try:
    block = dbus.Interface(
        dbus.SessionBus().get_object('com.dubstepdish.i3dstatus', blockpath),
        'com.dubstepdish.i3dstatus.Block'
    )

    clipboard.connect('owner-change', on_owner_change)

    GLib.MainLoop().run()
finally:
    i3dstatus.remove_block(blockpath)
