#!/usr/bin/env python3
import time
from i3dstatus.utils import get_config, make_block

config = get_config('clock')

time_format = config.get('format', '%m/%d <b>%H:%M</b>')

last_time = ''

with make_block(
    'clock',
    {
        "name": "clock",
        "markup": "pango"
    }
) as bgen:
    block = bgen()

    while True:
        time_string = time.strftime(time_format)
        if time_string != last_time:
            last_time = time_string
            block.update({"full_text": time.strftime(time_format)})
        time.sleep(1)
