#!/usr/bin/env python3
import time
import os

from i3dstatus.block import Block

block = Block(os.path.basename(__file__))

time_format = '%m/%d <b>%H:%M</b>'

if 'format' in block.config:
    time_format = block.config['format']

last_time = ''

while True:
    time_string = time.strftime(time_format)
    if time_string != last_time:
        last_time = time_string
        block.show(time.strftime(time_format),
            markup='pango',
        )
    time.sleep(1)
