#!/usr/bin/env python3

from i3dstatus.block import Block

import time
import os
import asyncio


async def main():
    block = await Block(os.path.basename(__file__)).connect()

    time_format = '%m/%d <b>%H:%M</b>'

    if 'format' in block.config:
        time_format = block.config['format']

    last_time = ''

    while True:
        time_string = time.strftime(time_format)
        if time_string != last_time:
            last_time = time_string
            await block.show(
                time.strftime(time_format),
                markup='pango',
            )

        await asyncio.sleep(1)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
