#!/usr/bin/env python3
import dbus
import time
import json
import netifaces
import os
from i3dstatus.block import Block

block = Block(os.path.basename(__file__))

default_up = '%iface: %ip'
default_down = '%iface: <b>down</b>'

config = dict(block.config)

if not config:
    config = {}
    # find the first ethernet interface
    for iface in netifaces.interfaces():
        if iface.startswith('lo'):
            # loopback device
            continue

        config[iface] = {'format-up': default_up, 'format-down': default_down}
        break

while True:
    for iface, opts in config.items():
        addr = netifaces.ifaddresses(iface)
        if netifaces.AF_INET in addr:
            # device is up
            ip = 'no ip'

            if 'addr' in addr[netifaces.AF_INET][0]:
                ip = addr[netifaces.AF_INET][0]['addr']

            context = {
                'ip': ip,
                'iface': iface,
            }

            block.show(opts['format-up'], instance=iface,
                    context=context, markup='pango')
        else:
            # device is down
            context = {
                'iface': iface,
            }
            block.show(opts['format-down'], instance=iface,
                    context=context, markup='pango')

    time.sleep(5)
