#!/usr/bin/env python3

import i3ipc
import dbus
import json
import cgi

i3dstatus = dbus.Interface(dbus.SessionBus().get_object(
                           'com.dubstepdish.i3dstatus',
                           '/com/dubstepdish/i3dstatus'),
                           'com.dubstepdish.i3dstatus')

i3 = i3ipc.Connection()

scratchpad_format = 'scratchpad: <b>%classes</b>'

config = json.loads(i3dstatus.get_config('scratchpad'))

if 'format' in config:
    scratchpad_format = config['format']

last_full_text = ''


def show_block():
    global last_full_text
    block = {"name": "scratchpad", "markup": "pango", "full_text": ""}

    scratchpad = i3.get_tree().scratchpad().leaves()

    if scratchpad:
        classes = []
        has_urgent = False
        urgent_fmt = '<span color="red">{}</span>'

        for l in scratchpad:
            window_class = cgi.escape(l.window_class)
            if l.urgent:
                has_urgent = True
                classes.append(urgent_fmt.format(window_class))
            else:
                classes.append(window_class)

        full_text = scratchpad_format.replace('%classes',
                                              ', '.join(classes))
        if has_urgent:
            full_text = full_text.replace('%count',
                                          urgent_fmt.format(len(scratchpad)))
        else:
            full_text = full_text.replace('%count', str(len(scratchpad)))

        block['full_text'] = full_text

    if block['full_text'] != last_full_text:
        last_full_text = block['full_text']
        i3dstatus.show_block(block)


def on_move(i3, e):
    show_block()


def on_urgent(i3, e):
    show_block()

show_block()

i3.on('window::move', on_move)
i3.on('window::urgent', on_urgent)

i3.main()
