#!/usr/bin/env python3

import i3ipc
import cgi
from i3dstatus.utils import get_config, make_block

i3 = i3ipc.Connection()

config = get_config('scratchpad')

scratchpad_format = config.get('format', 'scratchpad: <b>%classes</b>')


def show_block(block):

    scratchpad = i3.get_tree().scratchpad().leaves()
    print(scratchpad)

    full_text = "(None)"

    if scratchpad:
        classes = []
        has_urgent = False
        urgent_fmt = '<span color="red">{}</span>'

        for l in scratchpad:
            window_class = cgi.escape(l.window_class)
            if l.urgent:
                has_urgent = True
                classes.append(urgent_fmt.format(window_class))
            else:
                classes.append(window_class)

        full_text = scratchpad_format.replace('%classes',
                                              ', '.join(classes))
        if has_urgent:
            full_text = full_text.replace('%count',
                                          urgent_fmt.format(len(scratchpad)))
        else:
            full_text = full_text.replace('%count', str(len(scratchpad)))

    print(full_text)
    block.set_full_text(full_text)


def on_event(i3, e):
    global block
    show_block(block)


with make_block(
    "scratchpad",
    {"name": "scratchpad", "markup": "pango"}
) as bgen:
    block = bgen()

    show_block(block)

    i3.on('window::move', on_event)
    i3.on('window::urgent', on_event)
    i3.on('window::floating', on_event)

    i3.main()
