#!/usr/bin/env python3
import time, dbus, yaml, os
from threading import Timer

time_format = '%m/%d <b>%H:%M</b>'

try:
    f = open("{}/.i3-dstatus.conf".format(os.path.expanduser('~')))
    config = yaml.safe_load(f)
    if 'clock' in config:
        if 'format' in config['clock']:
            time_format = config['clock']['format']
    f.close()
except FileNotFoundError:
    pass

i3dstatus = dbus.Interface(dbus.SessionBus().get_object('com.dubstepdish.i3dstatus',
                                                        '/com/dubstepdish/i3dstatus'),
                           'com.dubstepdish.i3dstatus')

def on_tick():
    i3dstatus.show_block({"name": "clock", "full_text": time.strftime(time_format)})
    Timer(1.0, on_tick).start()

on_tick()
