#!/usr/bin/env python3
import time, dbus, json, os
from threading import Timer

i3dstatus = dbus.Interface(dbus.SessionBus().get_object('com.dubstepdish.i3dstatus',
                                                        '/com/dubstepdish/i3dstatus'),
                           'com.dubstepdish.i3dstatus')

time_format = '%m/%d <b>%H:%M</b>'

config = json.loads(i3dstatus.get_config('clock'))

if 'format' in config:
    time_format = config['format']

def on_tick():
    i3dstatus.show_block({"name": "clock", "full_text": time.strftime(time_format)})
    Timer(1.0, on_tick).start()

on_tick()
