#!/usr/bin/env python3
import time, dbus, yaml, os
from threading import Timer

time_format = '%m/%d %H:%M'

try:
    f = open("{}/.i3-dstatus.conf".format(os.path.expanduser('~')))
    config = yaml.safe_load(f)
    if 'clock' in config:
        if 'format' in config['clock']:
            time_format = config['clock']['format']
    f.close()
except FileNotFoundError:
    pass

bus = dbus.SessionBus()

def show_block(block):
    service = bus.get_object('com.dubstepdish.i3dstatus', '/com/dubstepdish/i3dstatus')
    service_method = service.get_dbus_method('show_block', 'com.dubstepdish.i3dstatus')
    service_method(block)

def on_tick():
    block = { "name": "clock", "full_text": time.strftime(time_format) }
    show_block(block)
    Timer(1.0, on_tick).start()

on_tick()
